# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

language: go

os:
- linux
- osx

go:
- "1.13"

git:
  depth: 1

go_import_path: sigs.k8s.io/cli-utils

script:
  - make lint test

notifications:
  email: false
