# Example configuration for the webserver
# at https://github.com/monopole/hello

namespace: default

commonLabels:
  app: hello  

resources:
- deployment.yaml
- service.yaml
- configMap.yaml

inventory:
  type: ConfigMap
  configMap:
    name: the-inventory
    namespace: default
