apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dynamic.cli.sigs.k8s.io
spec:
  group: resourcecommands.dynamic.cli.sigs.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: resourcecommands
    singular: resourcecommand
    kind: ResourceCommand
