name: Go
on: [push]
jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install deps
      run: |
        go get golang.org/x/tools/cmd/stringer
        go install golang.org/x/tools/cmd/stringer
        go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.19.1
        go install github.com/golangci/golangci-lint/cmd/golangci-lint
        go get get github.com/google/addlicense
        go install get github.com/google/addlicense

    - name: Run tests
      run: |
        make
